_wandb:
    value:
        cli_version: 0.21.3
        e:
            ylw4gyyebv43v9s70fnuab1kv94fvqd1:
                args:
                    - --device-batch-size=16
                    - --run=nanochat_sft_96h_h100_fois15
                    - --matrix-lr
                    - "0.03"
                    - --embedding-lr
                    - "0.45"
                    - --unembedding-lr
                    - "0.006"
                    - --num-iterations
                    - "969"
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "30333054976"
                        used: "21432909824"
                email: andrea.binetruy@gmail.com
                executable: /home/abinetru/nanochat/.venv/bin/python3
                git:
                    commit: 0aaca56805eb13f6e6e1fff789a08086902f12ab
                    remote: https://github.com/karpathy/nanochat.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-81ce2834-5708-7c30-ca85-ec061a0034e6
                host: esterel37-1.sophia.grid5000.fr
                memory:
                    total: "540808548352"
                os: Linux-5.10.0-38-amd64-x86_64-with-glibc2.31
                program: -m scripts.c2_1c_chat_sft
                python: CPython 3.10.20
                root: /home/abinetru/nanochat
                startedAt: "2026-07-02T09:11:46.521955Z"
                writerId: ylw4gyyebv43v9s70fnuab1kv94fvqd1
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 49
                - 51
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
chatcore_every:
    value: 200
chatcore_max_cat:
    value: -1
chatcore_max_sample:
    value: 24
device_batch_size:
    value: 16
device_type:
    value: ""
embedding_lr:
    value: 0.45
eval_every:
    value: 200
eval_tokens:
    value: 20971520
final_lr_frac:
    value: 0
gsm8k_epochs:
    value: 4
init_lr_frac:
    value: 0.8
load_optimizer:
    value: 1
matrix_lr:
    value: 0.03
max_seq_len:
    value: null
mmlu_epochs:
    value: 3
model_step:
    value: null
model_tag:
    value: null
num_iterations:
    value: 969
run:
    value: nanochat_sft_96h_h100_fois15
total_batch_size:
    value: null
unembedding_lr:
    value: 0.006
warmdown_ratio:
    value: 0.5
warmup_ratio:
    value: 0
