_wandb:
    value:
        cli_version: 0.21.3
        e:
            qy9hr1zi7ubj94ypnt0tnbkkqp7vcbv1:
                args:
                    - --depth=12
                    - --window-pattern=L
                    - --target-param-data-ratio=100
                    - --device-batch-size=16
                    - --fp8
                    - --run=croissant_H100_150tok
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "30333186048"
                        used: "20895539200"
                email: andrea.binetruy@gmail.com
                executable: /home/abinetru/nanochat/.venv/bin/python3
                git:
                    commit: 0aaca56805eb13f6e6e1fff789a08086902f12ab
                    remote: https://github.com/karpathy/nanochat.git
                gpu: NVIDIA H100 NVL
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "100485038080"
                      name: NVIDIA H100 NVL
                      uuid: GPU-0ae4c2f2-0689-b3b4-c194-7cbf00810973
                host: musa-6.sophia.grid5000.fr
                memory:
                    total: "538661629952"
                os: Linux-5.10.0-38-amd64-x86_64-with-glibc2.31
                program: -m scripts.base_train
                python: CPython 3.10.20
                root: /home/abinetru/nanochat
                startedAt: "2026-07-08T00:55:48.133231Z"
                writerId: qy9hr1zi7ubj94ypnt0tnbkkqp7vcbv1
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 49
            "2":
                - 1
                - 49
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
aspect_ratio:
    value: 64
core_metric_every:
    value: 2000
core_metric_max_per_task:
    value: 500
depth:
    value: 12
device_batch_size:
    value: 16
device_type:
    value: ""
embedding_lr:
    value: 0.3
eval_every:
    value: 250
eval_tokens:
    value: 41943040
final_lr_frac:
    value: 0.05
fp8:
    value: true
fp8_recipe:
    value: tensorwise
head_dim:
    value: 128
matrix_lr:
    value: 0.02
max_seq_len:
    value: 2048
model_tag:
    value: null
num_iterations:
    value: -1
resume_from_step:
    value: -1
run:
    value: croissant_H100_150tok
sample_every:
    value: 2000
save_every:
    value: -1
scalar_lr:
    value: 0.5
target_flops:
    value: -1
target_param_data_ratio:
    value: 100
total_batch_size:
    value: -1
unembedding_lr:
    value: 0.008
warmdown_ratio:
    value: 0.65
warmup_steps:
    value: 40
weight_decay:
    value: 0.28
window_pattern:
    value: L
